// Generated by CoffeeScript 1.7.1
'use strict';
var StarterMobileGenerator, chalk, path, replace, yeoman, yosay;

yeoman = require('yeoman-generator');

yosay = require('yosay');

chalk = require('chalk');

path = require('path');

replace = require('replace');

StarterMobileGenerator = yeoman.generators.Base.extend({
  constructor: function() {
    return yeoman.generators.Base.apply(this, arguments);
  },
  init: function() {
    this.log(yosay('Welcome to the marvellous ' + chalk.red('Starter Mobile') + ' generator!'));
    return this.templatedata = {};
  },
  askForApplicationName: function() {
    var done, prompts;
    done = this.async();
    prompts = [
      {
        name: 'applicationName',
        message: 'What\'s the name of your mobile application?'
      }
    ];
    return this.prompt(prompts, (function(props) {
      this.props = props;
      return done();
    }).bind(this));
  },
  askForTargetPlatforms: function() {
    var done, prompts;
    done = this.async();
    prompts = [
      {
        type: 'checkbox',
        name: 'targetPlatforms',
        message: 'Would you like to enable this option?',
        choices: ['iPhone', 'Android', 'Windows Phone']
      }
    ];
    return this.prompt(prompts, (function(props) {
      this.props = props;
      return done();
    }).bind(this));
  },
  install: function() {
    return this.sourceRoot(path.join(__dirname, './templates/app'));
  },
  end: function() {
    this.log('\n');
    this.log('Your project is now created, you can use the following commands to get going');
    this.log(chalk.green('    dnu restore'));
    this.log(chalk.green('    dnu build'));
    this.log(chalk.green('    dnx . run') + ' for console projects');
    return this.log(chalk.green('    dnx . kestrel') + ' or ' + chalk.green('dnx . web') + ' for web projects');
  }
});

module.exports = StarterMobileGenerator;
